name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16, 18]

        steps:
            - uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v2

            - uses: ./.github/actions/setup-and-cache
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install & Build
              run: |
                  pnpm install
                  pnpm build

            - name: Lint
              run: pnpm lint

            - name: Unit Tests
              run: pnpm test
